---
title: "0109_modeling"
author: "chanwoo"
date: '2020 1 9 '
output: html_document
---

```{r setting, include=FALSE}
# 전처리 패키지
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
# 시각화 패키지
library(ggplot2)
# 마크다운 패키지
library(DT)
library(knitr)
# 텍스트 마이닝 패키지
library(tidytext)
library(KoNLP)
# 모델링 패키지
library(caret)
library(naivebayes)
# 모델링 평가
library(ROCR)

# 데이터 샘플링을 위해 새롭게 불러들인다.
data = read.csv("../data/train.csv")
```

```{r}

data$length = data$text %>% str_length() # 문자길이

data$TML = ifelse(data$length > 400, 1, 0) # X

# 넘버링
data$text = data$text %>% str_replace_all("[\\d.]+\\d+%", " ") # %(백분율) 제거
numbering_str = "\\d{1,2}\\.[^\\d]" # 넘버링 정규표현식 
# 넘버링 더미변수
data = data %>% mutate(numbering = data$text %>% str_extract_all(numbering_str) %>% 
                       sapply(length) %>%
                       sapply(function(x){
                         ifelse(x>1, # 넘버링은 최소 2개 이상이어야 함
                                1,
                                0)
                       }))


# 괄호 빈도
bracket_str = "\\(.*?\\)"
# 괄호 빈도 변수 생성
data$bracket_freq = data$text %>% str_extract_all(bracket_str) %>% sapply(length)

# 전문용어 빈도
specialty_terms_str = paste(c("론", "원리금", "여신","한도","사기","최저","대출","KISA"), collapse = "|")
data$specialty_terms_freq = data$text %>% str_extract_all(specialty_terms_str) %>% sapply(length)


# 올림 변수 추가
data$to = data$text %>% str_detect("올림") %>% ifelse(1, 0)

# y factor화
data$smishing = as.factor(data$smishing)
```

# data split
```{r}
index_train = createDataPartition(data$smishing, p=.7, list=F)

train = data[index_train, ]
test = data[-index_train, ]

train %>% dim
test %>% dim
```

# 학습
```{r}
# 첫번째 방법
naive_model = naive_bayes(smishing ~ TML + bracket_freq + specialty_terms_freq + to, train)
naive_model

# 두번째 방법 (다른 패키지 다운 받지 않더라도 100여개의 모델들을 적용시킬 수 있음)
modelFit = caret::train(smishing ~ TML + bracket_freq + specialty_terms_freq + to,
                        train,
                        method = 'naive_bayes')
modelFit
```

# 적용
```{r}
test$pred = predict(modelFit, newdata = test)
confusionMatrix(test$pred, test$smishing)
```


# 모델링 저장
```{r}
save(modelFit, # 학습 모델
     data, # 원본 데이터셋
     train, test, # 학습에 사용했던 데이터셋
     file = "../data/RData/0109_naive_model.RData")

save(data, file = "../data/RData/origin.RData")
```

